-- MySQL Script generated by MySQL Workbench
-- Tue Apr  8 11:53:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema real_estate_management_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema real_estate_management_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `real_estate_management_system` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `real_estate_management_system` ;

-- -----------------------------------------------------
-- Table `real_estate_management_system`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `real_estate_management_system`.`users` ;

CREATE TABLE IF NOT EXISTS `real_estate_management_system`.`users` (
  `User_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Phone` DOUBLE NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`User_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `real_estate_management_system`.`agents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `real_estate_management_system`.`agents` ;

CREATE TABLE IF NOT EXISTS `real_estate_management_system`.`agents` (
  `ID` INT NOT NULL,
  `User_ID` INT NOT NULL,
  `License_number` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `agents_idx` ON `real_estate_management_system`.`agents` (`User_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `real_estate_management_system`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `real_estate_management_system`.`customers` ;

CREATE TABLE IF NOT EXISTS `real_estate_management_system`.`customers` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`User_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `real_estate_management_system`.`leases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `real_estate_management_system`.`leases` ;

CREATE TABLE IF NOT EXISTS `real_estate_management_system`.`leases` (
  `ID` INT NOT NULL,
  `User_ID` INT NOT NULL,
  `Property_ID` INT NOT NULL,
  `Landlord_ID` INT NOT NULL,
  `Start_Date` DATE NOT NULL,
  `End_Date` DATE NOT NULL,
  `Monthly_Rent` DOUBLE NOT NULL,
  `Security_Deposit` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `leases_idx` ON `real_estate_management_system`.`leases` (`User_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `real_estate_management_system`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `real_estate_management_system`.`orders` ;

CREATE TABLE IF NOT EXISTS `real_estate_management_system`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `order_date` DATE NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `orders_ibfk_1` ON `real_estate_management_system`.`orders` (`customer_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `real_estate_management_system`.`properties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `real_estate_management_system`.`properties` ;

CREATE TABLE IF NOT EXISTS `real_estate_management_system`.`properties` (
  `ID` INT NOT NULL,
  `User_ID` INT NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Description` TEXT NOT NULL,
  `Address` TEXT NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  `Zip_Code` VARCHAR(45) NOT NULL,
  `Price` DOUBLE NOT NULL,
  `Size_sqft` DOUBLE NOT NULL,
  `Bedrooms` INT NOT NULL,
  `Bathrooms` INT NOT NULL,
  `Property_Type` VARCHAR(50) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `properties_idx` ON `real_estate_management_system`.`properties` (`User_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `real_estate_management_system`.`reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `real_estate_management_system`.`reviews` ;

CREATE TABLE IF NOT EXISTS `real_estate_management_system`.`reviews` (
  `ID` INT NOT NULL,
  `User_ID` INT NOT NULL,
  `Property_ID` VARCHAR(45) NOT NULL,
  `Review_Text` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `reviews_idx` ON `real_estate_management_system`.`reviews` (`User_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `real_estate_management_system`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `real_estate_management_system`.`roles` ;

CREATE TABLE IF NOT EXISTS `real_estate_management_system`.`roles` (
  `ID` INT NOT NULL,
  `User_ID` INT NOT NULL,
  `Role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `roles_idx` ON `real_estate_management_system`.`roles` (`User_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `real_estate_management_system`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `real_estate_management_system`.`transaction` ;

CREATE TABLE IF NOT EXISTS `real_estate_management_system`.`transaction` (
  `ID` INT NOT NULL,
  `User_ID` INT NOT NULL,
  `Buyer_ID` INT NOT NULL,
  `Seller_ID` INT NOT NULL,
  `Property_ID` INT NOT NULL,
  `Amount` DOUBLE NOT NULL,
  `Transaction_Date` DATE NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `transaction_idx` ON `real_estate_management_system`.`transaction` (`User_ID` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
